name: Publish to pub.dev

# on:
#   push:
#     tags:
#       - '[0-9]+.[0-9]+.[0-9]+'

on:
    push:
      branches:
        - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.2'
      - name: Install dependencies
        run: flutter pub get
    #   - name: Analyze
    #     run: flutter analyze
    #   - name: Run tests
    #     run: flutter test
      - name: Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./pub_login.sh
      # - name: Check Publish Warnings
      #   run: flutter pub publish --dry-run

      - name: Debug Credentials
        run: cat ~/.pub-cache/credentials.json

      - name: Publish Package
        run: flutter pub publish -f --credentials ~/.pub-cache/credentials.json
